### ISSUE TITLE
iOS 14 support

### ISSUE THREAD

**Issue by c19x** [vmware/herald-for-ios#35]
Location permission mandatory for BLE operation on iOS 14

Practical experiments have discovered that without location permission, a background iOS 14 device is discoverable, and connectable by other iOS and Android devices, but service discovery will not report any services, thus characteristic read / write / notify is not possible. However, RSSI is still obtainable from the advert.

While location permission was optional for HERALD on iOS 13 or earlier, it should now be mandatory.

**Comment by adamfowleruk** [comment]
Accepted due to iOS 14.2 change of behaviour
