### ISSUE TITLE
Support for multiple service UUID

### ISSUE THREAD

**Issue by c19x** [vmware/herald-for-ios#42]
- Adopters may have used their own service UUID in their existing solution.
- HERALD encourages a standard service UUID across all adopters for international interoperability.
- Temporary solution is for adopter to use their existing service UUID in HERALD.
- Support for multiple service UUIDs will ease migration to common service UUID.

**Comment by adamfowleruk** [comment]
Accepted. Related to #33 and dependent upon it.
Recommend this is actioned after #33 is completed.

**Comment by adamfowleruk** [comment]
Legacy characteristic already supported. Not added legacy service UUID yet.

**Comment by c19x** [comment]
Closed by #107
