### ISSUE TITLE
Provide user of demo app an indication of their social mixing score

### ISSUE THREAD

**Issue by c19x** [vmware/herald-for-ios#7]
1. Database storage for contacts with automatic deletion according to retention period
2. Histogram of RSSI and duration for any timespan within retention period
3. Fit normal distribution over histogram
4. Scale histogram
5. Compute social mixing score for histogram

**Comment by adamfowleruk** [comment]
[Who]  As an application user
[What] I would like a daily indication of my social mixing score (like a step counter)
[Value] So I can make an informed decision as to the level of risk I am at to infection/exposure on a day by day basis

Note: These scores are not comparable between phones/people - they just need to be relative scores for that person on a day by day basis.
