### ISSUE TITLE
Test results table missing scenario

### ISSUE THREAD

**Issue by HendX** [vmware/herald-for-ios#81]
Just reading the test results in the project README, there is no scenario listed for:

“iOS only (Location OFF)”

(i.e. location permissions denied, and no nearby Android device).

For completeness of this table, do you think this scenario should be included? And perhaps also a scenario where there is a mix of location on/off, with no Android nearby?

**Comment by adamfowleruk** [comment]
The README is just an overview document. Please review the website and the description of the 'formal test procedure' which details our major version tests. These tests with multiple devices are always carried out with Location permission and the AwakeSensor disabled.

Herald does not require the Location permission in order to provide a high degree of contacts in real world scenarios.

**Comment by HendX** [comment]
(Sorry, could you link me to this document, I’m having trouble finding it.)

Can you please clarify though - based on everything we know about how Bluetooth on iOS works (many of those noted on the Herald web site), wouldn’t the scenario I’ve outlined here clock in at a number below 100%?

And if so, would that not invalidate the claim of “detects 100% of app users”?

> Herald does not require the Location permission in order to provide a high degree of contacts in real world scenarios.

“High degree” is not 100% though, right?

**Comment by HendX** [comment]
Disregard request for URL, found it:

https://vmware.github.io/herald/efficacy/method

**Comment by HendX** [comment]
@adamfowleruk genuinely looking for an answer to my questions above.

I'm struggling to understand how the "green circle graphic" at the top of the README derives its "100% Detection" label.

The scenario I've outlined above demonstrates the key limitation to Bluetooth on iOS, so unless I'm misunderstanding, omitting it is omitting the most important and relevant piece of information.

I also don't see any mention of this scenario in the document you've linked to - it just shows how you reached the numbers that _are_ being displayed.

There is an intricate amount of detail and care put into so much of this project, but the claim that it detects 100% of devices at the top of the README was the immediate thing that stood out to me with this project, especially when it ("100% device detection") was repeated by senior Australian Government politicians.

Decisions that affect the lives of millions of people in Australia have been made as a result of this claim, so I think it's reasonable for it to attract some scrutiny.
 
Please clarify.

**Comment by HendX** [comment]
@adamfowleruk I’m unsure how to interpret your radio silence on this issue, given your attentiveness on every other issue raised on this and the Android trackers.

It seems antithetical to the code of conduct that you’ve invoked multiple times against other contributors (@jimmo) in recent days.

Once again, I’m pressing for this because the update to COVIDSafe using Herald is now out in Australia, despite the numerous questions that have also gone unanswered by the authors of that app.

The “100%” claim seems pretty central to the decision-making behind the use of Herald.

The claim seems outlandish to me, for reasons highlighted above, so as author of the code and documentation, you should be able to clear this up.
